/*
 * message code define
 * if you are changing this file, mind to rebuild both Frontend and Backend later
 */

namespace Common
{
    public enum Command
    {
        NONE,
        SBEGIN = 0,
        S_PLAYER_REGISTER,
        S_PLAYER_ENTER,
        S_ITEM_SPAWN,
        S_SPAWN,
        S_PLAYER_RESPAWN,
        S_PLAYER_ACTION,
        S_ENTITY_DESTROY,
        S_PLAYER_MOVE,
        S_SPRITE_MOVE,
        S_JUMP,
        S_ATTACK,
        S_EQUIP_WEAPON,
        S_HIT,
        S_TAKE_ITEM,
        S_EXIT,
        S_SPRITE_DIE,
        S_PLAYER_DIE,
        S_TIP_INFO,
        S_PLAYER_ATTRIBUTE,
        S_TRIGER_STATUS,
        S_TRIGER_ON_ENTER,
        S_OTHER_PLAYER_ENTER,
        S_OTHER_PLAYER_EXIT,
        S_ONLINE_PLAYERS,
        S_CHAT_MESSAGE,
        S_GET_ITEM,
        S_PLAYER_INVENTORY,
        S_PLAYER_EQUIP_ITEM,
        S_PLAYER_UNEQUIP_ITEM,
        S_PLAYER_DROP_ITEM,
        S_PLAYER_CHANGE_ITEM,
        S_PLAYER_USE_ITEM,
        S_GET_TMALL_ITEMS,
        S_BUY_TMALL_ITEMS,
        S_GET_MARKET_ITEMS,
        S_SELL_MARKET_ITEM,
        S_BUY_MARKET_ITEM,
        S_BROADCAST_MESSAGE,
        S_AWARD_SILVER,
        S_PLAYER_BEAT,
        S_CHANGE_SCENE,
        SEND,

        CBEGIN,
        C_HEART_BEAT,
        C_LOGIN,
        C_REGISTER,
        C_PLAYER_EXIT,
        C_PLAYER_ENTER,
        C_PLAYER_ATTACK,
        C_PLAYER_JUMP,
        C_PLAYER_MOVE,
        C_PLAYER_TAKE,
        C_TRIGER_ON_ENTER,
        C_POSITION_REVISE,
        C_ENEMY_CLOSING,
        C_DAMAGE,
        C_CHAT_MESSAGE,
        C_CREATE_ITEM,
        C_PLAYER_EQUIP_ITEM,
        C_PLAYER_UNEQUIP_ITEM,
        C_PLAYER_DROP_ITEM,
        C_PLAYER_CHANGE_ITEM,
        C_PLAYER_USE_ITEM,
        C_PLAYER_ATTRIBUTE,
        C_GET_TMALL_ITEMS,
        C_BUY_TMALL_ITEMS,
        C_GET_MARKET_ITEMS,
        C_BUY_MARKET_ITEM,
        C_SELL_MARKET_ITEM,
        C_CHANGE_SCENE,
        CEND,

        DEBUGGING, // THE FOLLOWING MESSEGES ARE FOR DEBUGGING
        C_FIND_PATH,
        S_FIND_PATH,

        CMD_END, // DO NOT GREATER THAN UINT_MAX !!!
    }
}
